title: Data Mining & Science Research Venues Deadlines
description: Countdowns to top Data Mining & Science Research Venues deadlines.
author: Jeongwhan Choi

domain: "dm-deadlines.github.io"
baseurl: ""

github_username: dm-deadlines
github_repo: dm-deadlines.github.io

markdown: kramdown